# Generated by Django 2.2.2 on 2019-07-06 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0002_auto_20190620_0118'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='hint',
            field=models.TextField(blank=True, max_length=30),
        ),
    ]
