# Generated by Django 2.2.2 on 2019-07-07 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0003_profile_hint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='hint',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
    ]
