# Generated by Django 2.2.2 on 2019-06-24 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MemberPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=60)),
                ('resource', models.CharField(max_length=60)),
                ('monthly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('overage_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('Semi_annual', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('Annual_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
            ],
        ),
    ]
