# Generated by Django 2.2.2 on 2019-06-24 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberpackage',
            name='Annual_rate',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='memberpackage',
            name='Semi_annual',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='memberpackage',
            name='monthly_rate',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='memberpackage',
            name='overage_rate',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
