# Generated by Django 2.2.2 on 2019-06-25 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0006_auto_20190625_0551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='member_package',
        ),
        migrations.AddField(
            model_name='membership',
            name='package_name',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
