# Generated by Django 2.2.2 on 2019-06-25 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0008_auto_20190625_0650'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='monthly_rate',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='month_rate', to='member.MemberPackage'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='package_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='pkg_name', to='member.MemberPackage'),
        ),
    ]
