# Generated by Django 2.2.2 on 2019-06-25 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0010_remove_membership_monthly_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
