# Generated by Django 2.2.2 on 2019-06-26 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0011_membership_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='total',
        ),
        migrations.AlterField(
            model_name='memberpackage',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='foo', to='member.MemberResources'),
        ),
    ]
