# Generated by Django 2.2.2 on 2019-06-26 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0012_auto_20190626_0308'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='membership',
            name='notes',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
