# Generated by Django 2.2.2 on 2019-06-26 04:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('member', '0013_auto_20190626_0333'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_ts', models.DateTimeField(auto_now_add=True)),
                ('closed_ts', models.DateTimeField(blank=True, null=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('due_date', models.DateField()),
                ('comment', models.TextField(blank=True, help_text='Public comments visible by user', null=True)),
                ('note', models.TextField(blank=True, help_text='Private notes about this bill', null=True)),
                ('in_progress', models.BooleanField(default=False, help_text="Mark a bill as 'in progress' indicating someone is working on it")),
                ('mark_paid', models.BooleanField(default=False, help_text='Mark a bill as paid even if it is not')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('total_tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('total_paid', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('total_owed', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='bills', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BillLineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('custom', models.BooleanField(default=False)),
                ('bill', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='member.UserBill')),
            ],
        ),
    ]
