# Generated by Django 2.2.2 on 2019-06-26 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0017_auto_20190626_0534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbill',
            name='package_name',
        ),
    ]
