# Generated by Django 2.2.2 on 2019-06-26 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0018_remove_userbill_package_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbill',
            name='mem_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='mem_name', to='member.Membership'),
        ),
    ]
