# Generated by Django 2.2.2 on 2019-06-27 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0019_userbill_mem_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbill',
            name='mem_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='m_name', to='member.Membership'),
        ),
    ]
